"""Scene model: a canvas made of named layers, each holding a list of drawing ops.

A scene is plain data so it can be written by hand, generated by a script, or
built up tool-call by tool-call by an AI model. It round-trips through JSON:

    {
      "width": 800, "height": 600, "background": "#ffffff",
      "layers": [
        {"name": "Sky", "opacity": 1.0, "visible": true,
         "ops": [{"op": "gradient", "kind": "linear", "x0": 0, "y0": 0,
                  "x1": 0, "y1": 600, "stops": [[0, "#0b1d51"], [1, "#ff9a5a"]]}]}
      ]
    }
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from .brushes import BRUSH_PARAMS, PRESETS
from .raster import BLEND_MODES

# Every painting op accepts these: opacity multiplies the op's alpha, lock_alpha only paints
# where the layer already has pixels (shade inside a shape), erase removes instead of paints.
COMMON = {"opacity", "lock_alpha", "erase", "clip"}
SHAPE = {"fill", "stroke", "width", "feather"} | COMMON
PATH = {"points", "paths"}  # one of the two is required

# op name -> (required keys, optional keys)
OP_SPECS: dict[str, tuple[set[str], set[str]]] = {
    "rect": ({"x", "y", "w", "h"}, SHAPE | {"radius"}),
    "ellipse": ({"cx", "cy", "rx", "ry"}, SHAPE | {"angle"}),
    "polygon": ({"points"}, SHAPE | {"smooth"}),
    "brush": (set(), PATH | BRUSH_PARAMS | COMMON | {"brush", "color", "seed"}),
    "stroke": (set(), PATH | COMMON | {"color", "width", "smooth"}),
    "line": ({"points"}, COMMON | {"color", "width"}),
    "hatch": ({"region"}, COMMON | BRUSH_PARAMS | {"brush", "color", "angle", "gap", "cross", "seed"}),
    "smudge": (set(), PATH | {"size", "strength", "hardness", "smooth", "lock_alpha", "clip"}),
    "gradient": ({"stops"}, COMMON | {"kind", "x0", "y0", "x1", "y1", "cx", "cy", "r"}),
    "scatter": ({"count"}, COMMON | {"region", "radius", "colors", "seed", "shape"}),
    "text": ({"x", "y", "text"}, COMMON | {"size", "color", "font", "anchor"}),
    "image": ({"path"}, COMMON | {"x", "y", "w", "h"}),
    "blur": ({"radius"}, {"clip"}),
    "form": ({"region"}, COMMON | {"bumps", "inflate", "light", "ramp", "wrap", "occlusion", "ambient", "bounce",
                                   "shine", "shine_size", "feather"}),
    "copy": ({"source"}, COMMON),
    "painterly": ({"source"}, COMMON | BRUSH_PARAMS | {"brush", "sizes", "threshold", "length", "curvature",
                                                        "flow_threshold",
                                                        "angle", "color_jitter", "grid", "blur", "region", "seed"}),
    "fill": ({"color"}, COMMON),
}

OP_HELP = {
    "brush": "Paint a stroke with a natural-media brush through points [[x,y] or [x,y,pressure 0..1], ...] "
    "(or many strokes at once via paths=[[...],[...]]). brush=one of BRUSHES; color; size (px); and any brush "
    "setting to override: hardness, flow, opacity, spacing, taper [start,end], jitter, wobble, grain, "
    "bristles, dryness, color_variation, pressure_size, pressure_opacity, smooth. Pressure makes lines "
    "swell and thin like a real stylus.",
    "hatch": "Shade a polygon region=[[x,y],...] with parallel strokes (default pencil): angle (deg), gap (px), "
    "cross=true for cross-hatching, plus brush/color/size and brush settings.",
    "smudge": "Blend (soften) existing paint on this layer along points/paths: size, strength 0..1. "
    "Use it to melt brush strokes together, e.g. skin tones. lock_alpha=true keeps paint from spreading "
    "past its edges.",
    "rect": "Rectangle x,y,w,h. fill, stroke, width, radius (rounded corners), feather (soft edge px).",
    "ellipse": "Ellipse at cx,cy with radii rx,ry, optionally rotated by angle (deg). fill, stroke, width, feather.",
    "polygon": "Closed shape through points. smooth=true makes an organic curved outline. fill, stroke, width, "
    "feather.",
    "stroke": "Simple hard round line through points with color and width (smooth by default).",
    "line": "Straight polyline through points with color and width.",
    "gradient": "Fill the layer with a gradient: kind='linear' (x0,y0 -> x1,y1) or 'radial' (cx,cy,r); "
    "stops=[[offset 0..1, color], ...]. Combine with lock_alpha to shade a shape you already painted.",
    "scatter": "Scatter count dots (shape 'circle' or 'star') in region [x,y,w,h]; radius=[min,max]; colors; seed.",
    "text": "Text at x,y. size (px), color, font (.ttf path), anchor (Pillow anchor, default 'la').",
    "image": "Place an image file (e.g. a reference photo or texture) at x,y, optionally resized to w,h.",
    "blur": "Gaussian-blur everything on this layer so far (glows, atmosphere, soft shadows).",
    "copy": "Paint another layer's pixels (or several layers flattened, or {path}) onto this one, e.g. a "
    "smooth study at low opacity over its painterly version, as a glaze. Takes opacity, clip, lock_alpha.",
    "form": "Paint a lit 3D form. region = silhouette points (smoothed); inflate = how rounded (px); "
    "bumps = [{x, y, rx, ry, h, angle, profile:'gauss'|'sphere'}] add mounds (h>0: cheekbone, nose, brow) "
    "and hollows (h<0: eye socket, mouth corner); light = [x, y, z] direction toward the light (y down, z "
    "toward viewer); ramp = [[0, shadow], [0.5, midtone], [1, light]] colours; wrap (soft terminator), "
    "occlusion, ambient, bounce = [color, strength] reflected light, shine / shine_size specular. "
    "Great as a hidden study layer that a painterly op then repaints.",
    "painterly": "Repaint a source with real brush strokes, big to small, following the form. source = a "
    "layer name (usually a hidden study layer of smooth shapes / forms), a list of layer names (flattened "
    "with their blend modes, e.g. a form plus a multiply colour layer), or {path, x, y, w, h} for an image "
    "file such as a reference photo. sizes = brush diameters, e.g. [28, 14, 7, 4]; threshold (0..1, lower = "
    "more strokes and detail); length = [min, max] stroke segments; curvature; angle (fixed direction, deg); "
    "brush + brush settings; region = polygon to limit where strokes start.",
    "fill": "Flood the whole layer with a color.",
    "common": "Painting ops also take opacity (0..1), lock_alpha (only paint where the layer already has "
    "paint), erase (remove paint instead of adding it), and clip: a selection the op is confined to, "
    "either [[x,y],...] or {points, smooth, feather, invert}.",
    "layers": "Layers take opacity and blend: " + ", ".join(BLEND_MODES) + ". A multiply layer is ideal for "
    "pencil/ink linework and shadows; screen/additive for light.",
}

BRUSH_HELP = {name: f"size {b.size:g}, hardness {b.hardness:g}" + (f", {b.bristles} bristles" if b.bristles else "")
              + (", paper grain" if b.grain else "") + (", builds up" if b.buildup else "")
              + (", wet edges" if b.wet_edge else "") for name, b in PRESETS.items()}


class SceneError(ValueError):
    pass


def validate_op(op: dict[str, Any]) -> dict[str, Any]:
    if not isinstance(op, dict) or "op" not in op:
        raise SceneError(f"each op must be an object with an 'op' key, got {op!r}")
    kind = op["op"]
    if kind not in OP_SPECS:
        raise SceneError(f"unknown op {kind!r}; expected one of {sorted(OP_SPECS)}")
    required, optional = OP_SPECS[kind]
    keys = set(op) - {"op"}
    missing = required - keys
    if missing:
        raise SceneError(f"op {kind!r} is missing {sorted(missing)}")
    unknown = keys - required - optional
    if unknown:
        raise SceneError(f"op {kind!r} does not accept {sorted(unknown)}")
    if PATH <= (required | optional) and not (keys & PATH):
        raise SceneError(f"op {kind!r} needs 'points' or 'paths'")
    if kind == "polygon" and len(op["points"]) < 3:
        raise SceneError("polygon needs at least 3 points")
    if kind == "hatch" and len(op["region"]) < 3:
        raise SceneError("hatch region needs at least 3 points")
    if kind in ("painterly", "copy"):
        src = op["source"]
        if not (isinstance(src, str) or (isinstance(src, list) and src and all(isinstance(n, str) for n in src))
                or (isinstance(src, dict) and "path" in src)):
            raise SceneError(kind + ' source must be a layer name, a list of layer names, or {"path": ...}')
    if op.get("brush") is not None and op["brush"] not in PRESETS:
        raise SceneError(f"unknown brush {op['brush']!r}; presets are {sorted(PRESETS)}")
    for path in op.get("paths", [op["points"]] if "points" in op else []):
        if not path or any(not isinstance(p, (list, tuple)) or len(p) not in (2, 3) for p in path):
            raise SceneError(f"op {kind!r}: points must be non-empty lists of [x, y] or [x, y, pressure]")
    return op


@dataclass
class Layer:
    name: str
    opacity: float = 1.0
    visible: bool = True
    ops: list[dict[str, Any]] = field(default_factory=list)
    blend: str = "normal"

    def __post_init__(self) -> None:
        if self.blend not in BLEND_MODES:
            raise SceneError(f"blend must be one of {BLEND_MODES}, got {self.blend!r}")

    def add(self, op: dict[str, Any]) -> None:
        self.ops.append(validate_op(op))

    def to_dict(self) -> dict[str, Any]:
        return {"name": self.name, "opacity": self.opacity, "visible": self.visible, "blend": self.blend,
                "ops": self.ops}

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> Layer:
        layer = cls(d["name"], float(d.get("opacity", 1.0)), bool(d.get("visible", True)),
                    blend=d.get("blend", "normal"))
        for op in d.get("ops", []):
            layer.add(op)
        return layer


@dataclass
class Scene:
    width: int
    height: int
    background: Any = "#ffffff"  # None for a transparent background
    layers: list[Layer] = field(default_factory=list)
    base_dir: Path | None = field(default=None, compare=False, repr=False)  # resolves relative file paths

    def __post_init__(self) -> None:
        if not (1 <= self.width <= 16384 and 1 <= self.height <= 16384):
            raise SceneError("canvas size must be between 1 and 16384 px per side")

    def layer(self, name: str) -> Layer:
        for layer in self.layers:
            if layer.name == name:
                return layer
        raise SceneError(f"no layer named {name!r}; layers are {[l.name for l in self.layers]}")

    def add_layer(self, name: str, opacity: float = 1.0, blend: str = "normal") -> Layer:
        if any(l.name == name for l in self.layers):
            raise SceneError(f"layer {name!r} already exists")
        layer = Layer(name, opacity, blend=blend)
        self.layers.append(layer)
        return layer

    def to_dict(self) -> dict[str, Any]:
        return {
            "width": self.width,
            "height": self.height,
            "background": self.background,
            "layers": [l.to_dict() for l in self.layers],
        }

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> Scene:
        scene = cls(int(d["width"]), int(d["height"]), d.get("background", "#ffffff"))
        for ld in d.get("layers", []):
            scene.layers.append(Layer.from_dict(ld))
        return scene

    def save(self, path: str | Path) -> None:
        Path(path).write_text(json.dumps(self.to_dict(), indent=2))

    @classmethod
    def load(cls, path: str | Path) -> Scene:
        scene = cls.from_dict(json.loads(Path(path).read_text()))
        scene.base_dir = Path(path).resolve().parent
        return scene
