"""Scene model: a canvas made of named layers, each holding a list of drawing ops.

A scene is plain data so it can be written by hand, generated by a script, or
built up tool-call by tool-call by an AI model. It round-trips through JSON:

    {
      "width": 800, "height": 600, "background": "#ffffff",
      "layers": [
        {"name": "Sky", "opacity": 1.0, "visible": true,
         "ops": [{"op": "gradient", "kind": "linear", "x0": 0, "y0": 0,
                  "x1": 0, "y1": 600, "stops": [[0, "#0b1d51"], [1, "#ff9a5a"]]}]}
      ]
    }
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

# op name -> (required keys, optional keys)
OP_SPECS: dict[str, tuple[set[str], set[str]]] = {
    "rect": ({"x", "y", "w", "h"}, {"fill", "stroke", "width", "radius"}),
    "ellipse": ({"cx", "cy", "rx", "ry"}, {"fill", "stroke", "width"}),
    "polygon": ({"points"}, {"fill", "stroke", "width"}),
    "line": ({"points"}, {"color", "width"}),
    "stroke": ({"points"}, {"color", "width", "smooth"}),
    "gradient": ({"stops"}, {"kind", "x0", "y0", "x1", "y1", "cx", "cy", "r"}),
    "scatter": ({"count"}, {"region", "radius", "colors", "seed", "shape"}),
    "text": ({"x", "y", "text"}, {"size", "color", "font", "anchor"}),
    "blur": ({"radius"}, set()),
    "fill": ({"color"}, set()),
}

OP_HELP = {
    "rect": "Rectangle at x,y of size w,h. Optional fill, stroke, width (outline px), radius (rounded corners).",
    "ellipse": "Ellipse centred at cx,cy with radii rx,ry. Optional fill, stroke, width.",
    "polygon": "Closed polygon through points [[x,y],...]. Optional fill, stroke, width.",
    "line": "Straight polyline through points with color and width.",
    "stroke": "Brush stroke through points with round caps; smooth=true (default) curves it through the points.",
    "gradient": "Fill the layer with a gradient. kind='linear' uses x0,y0 -> x1,y1; kind='radial' uses cx,cy,r. "
    "stops=[[offset 0..1, color], ...].",
    "scatter": "Scatter `count` dots (shape 'circle' or 'star') in region [x,y,w,h] (default whole canvas); "
    "radius=[min,max]; colors=[...]; seed for repeatability.",
    "text": "Draw text at x,y. Optional size (px), color, font (path to .ttf), anchor (Pillow anchor, default 'la').",
    "blur": "Gaussian-blur everything drawn on this layer so far (great for glows and soft shadows).",
    "fill": "Flood the whole layer with a color.",
}


class SceneError(ValueError):
    pass


def validate_op(op: dict[str, Any]) -> dict[str, Any]:
    if not isinstance(op, dict) or "op" not in op:
        raise SceneError(f"each op must be an object with an 'op' key, got {op!r}")
    kind = op["op"]
    if kind not in OP_SPECS:
        raise SceneError(f"unknown op {kind!r}; expected one of {sorted(OP_SPECS)}")
    required, optional = OP_SPECS[kind]
    keys = set(op) - {"op"}
    missing = required - keys
    if missing:
        raise SceneError(f"op {kind!r} is missing {sorted(missing)}")
    unknown = keys - required - optional
    if unknown:
        raise SceneError(f"op {kind!r} does not accept {sorted(unknown)}")
    if "points" in op and len(op["points"]) < (3 if kind == "polygon" else 1):
        raise SceneError(f"op {kind!r} needs more points")
    return op


@dataclass
class Layer:
    name: str
    opacity: float = 1.0
    visible: bool = True
    ops: list[dict[str, Any]] = field(default_factory=list)

    def add(self, op: dict[str, Any]) -> None:
        self.ops.append(validate_op(op))

    def to_dict(self) -> dict[str, Any]:
        return {"name": self.name, "opacity": self.opacity, "visible": self.visible, "ops": self.ops}

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> Layer:
        layer = cls(d["name"], float(d.get("opacity", 1.0)), bool(d.get("visible", True)))
        for op in d.get("ops", []):
            layer.add(op)
        return layer


@dataclass
class Scene:
    width: int
    height: int
    background: Any = "#ffffff"  # None for a transparent background
    layers: list[Layer] = field(default_factory=list)

    def __post_init__(self) -> None:
        if not (1 <= self.width <= 16384 and 1 <= self.height <= 16384):
            raise SceneError("canvas size must be between 1 and 16384 px per side")

    def layer(self, name: str) -> Layer:
        for layer in self.layers:
            if layer.name == name:
                return layer
        raise SceneError(f"no layer named {name!r}; layers are {[l.name for l in self.layers]}")

    def add_layer(self, name: str, opacity: float = 1.0) -> Layer:
        if any(l.name == name for l in self.layers):
            raise SceneError(f"layer {name!r} already exists")
        layer = Layer(name, opacity)
        self.layers.append(layer)
        return layer

    def to_dict(self) -> dict[str, Any]:
        return {
            "width": self.width,
            "height": self.height,
            "background": self.background,
            "layers": [l.to_dict() for l in self.layers],
        }

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> Scene:
        scene = cls(int(d["width"]), int(d["height"]), d.get("background", "#ffffff"))
        for ld in d.get("layers", []):
            scene.layers.append(Layer.from_dict(ld))
        return scene

    def save(self, path: str | Path) -> None:
        Path(path).write_text(json.dumps(self.to_dict(), indent=2))

    @classmethod
    def load(cls, path: str | Path) -> Scene:
        return cls.from_dict(json.loads(Path(path).read_text()))
